### ISSUE TITLE
下载失败 报错似乎与网络有关 但是自行试验链接外网和直ping sketchfab有链接

### ISSUE THREAD

**Issue by Naexen** [MiniKimmy/sketchfab_download#5]
step 1 ============ download model ============
Pending...

Traceback (most recent call last):
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1059: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sketchfab.com', port=443): Max retries exceeded with url: /3d-models/magical-mirai2019hatsune-miku-e8a9450e265e466ab856e3e8f8d529a0 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\naexen\Desktop\0\sketchfab_download\code\sketchfab_download.py", line 113, in <module>
    main(args)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\code\sketchfab_download.py", line 100, in main
    parse(args.url, args.output)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\code\sketchfab_download.py", line 57, in parse
    page = requests.get(url, headers=HEADERS, timeout=20).text
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\naexen\Desktop\0\sketchfab_download\bin\py\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='sketchfab.com', port=443): Max retries exceeded with url: /3d-models/magical-mirai2019hatsune-miku-e8a9450e265e466ab856e3e8f8d529a0 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out')))
err returnCode: 1

**Comment by Naexen** [comment]
ping sketchfab.com

正在 Ping sketchfab.com [13.227.73.79] 具有 32 字节的数据:
来自 13.227.73.79 的回复: 字节=32 时间=204ms TTL=238
来自 13.227.73.79 的回复: 字节=32 时间=196ms TTL=238
来自 13.227.73.79 的回复: 字节=32 时间=192ms TTL=238
来自 13.227.73.79 的回复: 字节=32 时间=172ms TTL=238

13.227.73.79 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 172ms，最长 = 204ms，平均 = 191ms

**Comment by Naexen** [comment]
突然发现关闭梯子就好了 但是decode出现了新问题
step 2 ============ decode blend ============
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
err returnCode: 1

**Comment by Naexen** [comment]
=================
开始生成激活上下文。
输入参数:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = zh-CN;zh-Hans;zh;en-US;en
	ManifestPath = C:\Users\naexen\Desktop\0\sketchfab_download\blender\blender.exe.Manifest
	AssemblyDirectory = C:\Users\naexen\Desktop\0\sketchfab_download\blender\
	Application Config File = 
-----------------
信息: 正在解析清单文件 C:\Users\naexen\Desktop\0\sketchfab_download\blender\blender.exe.Manifest。
	信息: 指令清单定义标识是 (null)。
	信息: 参考: Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"
信息: 正在解析参考 Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"。
	信息: 正在解析 ProcessorArchitecture amd64 的参考。
		信息: 正在解析区域性 Neutral 的参考。
			信息: 正在应用绑定策略。
				信息: 未找到发布服务器策略。
				信息: 未找到绑定策略重定向。
			信息: 开始程序集探测。
				信息: 未找到 WinSxS 中的程序集。
				信息: 尝试在 C:\Windows\assembly\GAC_64\Microsoft.VC90.OpenMP\9.0.21022.8__1fc8b3b9a1e18e3b\Microsoft.VC90.OpenMP.DLL 上探测指令清单。
				信息: 尝试在 C:\Users\naexen\Desktop\0\sketchfab_download\blender\Microsoft.VC90.OpenMP.DLL 上探测指令清单。
				信息: 尝试在 C:\Users\naexen\Desktop\0\sketchfab_download\blender\Microsoft.VC90.OpenMP.MANIFEST 上探测指令清单。
				信息: 尝试在 C:\Users\naexen\Desktop\0\sketchfab_download\blender\Microsoft.VC90.OpenMP\Microsoft.VC90.OpenMP.DLL 上探测指令清单。
				信息: 尝试在 C:\Users\naexen\Desktop\0\sketchfab_download\blender\Microsoft.VC90.OpenMP\Microsoft.VC90.OpenMP.MANIFEST 上探测指令清单。
				信息: 未找到区域性 Neutral 的指令清单。
			信息: 结束程序集探测。
	错误: 无法解析参考 Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"。
错误: 生成激活上下文失败。
结束生成激活上下文。

**Comment by MiniKimmy** [comment]
> 	错误: 无法解析参考 Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"。
> 
> 错误: 生成激活上下文失败。
> 
> 结束生成激活上下文。
> 
> 
> 
> 
这个同#1一样，可以在miscrosoft官网下载依赖
https://github.com/MiniKimmy/sketchfab_download/issues/1

**Comment by MiniKimmy** [comment]
> 突然发现关闭梯子就好了 但是decode出现了新问题
> 
> step 2 ============ decode blend ============
> 
> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
> 
> err returnCode: 1

网络问题确实无办法，可操作的地方最多是将timeout放宽，timeout在code/sketchfab_download.py改，默认是20s未响应就认为超时
